apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-build
spec:
  description: This task can be used to run a maven build.
  workspaces:
    - name: output
  params:
    - name: CONTEXT_DIR
      description: The directory within the repo for the soirces on which to run the maven.
      default: "."
  steps:
    - name: build
      image: maven:3.6.0-jdk-8-slim
      workingDir: $(workspaces.output.path)/$(params.CONTEXT_DIR)
      command:
        - /usr/bin/mvn
      args:
        - install
#      volumeMounts:
#        - name: maven-settings
#          mountPath: /var/mvn