apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pipeline-demo

resources:
  - workspaces/source-pvc.yaml
  - workspaces/maven-repo-pvc.yaml
  - pipelines/knative-app-pipeline.yaml
  - triggers/simple-quarkus-service-trigger-template.yaml
  - triggers/github-pr-trigger-binding.yaml
  - triggers/github-eventlistener.yaml