apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demoapp-cicd
resources:
  - volumes/shared-persistentVolumeClaim.yaml
  - volumes/maven-settings.yaml
  - tasks/maven-build-task.yaml
  - tasks/openshift-cli.yaml
  - tasks/apply-manifests.yaml
  - tasks/update-deployment.yaml
  - pipelines/build-deploy-maven-pipeline.yaml
