apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: api-image
spec:
  type: image
  params:
    - name: url
      value: default-route-openshift-image-registry.apps-crc.testing/demo-pipeline/pipelines-vote-api:latest