---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: simple-quarkus-service-trigger-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: main
    - name: gitrepositoryurl
      description: The git repository url ( "https://github.com/...")
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: simple-quarkus-service-deploy-
        labels:
          tekton.dev/pipeline: simple-quarkus-service-deploy
      spec:
        pipelineRef:
          name: knative-app-pipeline
        serviceAccountName: pipeline
        params:
          - name: IMAGE_NAME
            value: simple-quarkus-service
          - name: IMAGE_DEST
            value: image-registry.openshift-image-registry.svc:5000/serverless-pipeline-demo
          - name: APP_NAME
            value: simple-quarkus-service
          - name: GITHUB_REPO_URL
            value: '$(tt.params.gitrepositoryurl)'
          - name: GITHUB_REPO_REVISION
            value: '$(tt.params.gitrevision)'
        workspaces:
          - name: source
            persistentVolumeClaim:
              claimName: sources-pvc
          - name: m2-repo
            persistentVolumeClaim:
              claimName: maven-repo-pvc
