apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: This projec is use to contain the demo app and act as the development environment
    openshift.io/display-name: Demo App Dev
  name: demoapp-dev